apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: roboshop
  name: pod-reader
rules:
- apiGroups: [""] # "" indicates the core API group (v1)
  resources: ["pods",""]
  verbs: ["get", "watch", "list"]
