apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::315069654700:role/eksctl-roboshop-cluster-nodegroup--NodeInstanceRole-yZS3T6m0Z2Am
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      # - pod-reader
      # - service-reader
      # - secret-reader
      userarn: arn:aws:iam::490004616197:user/bhavana
      username: bhavana
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
  uid: 11571167-16ab-4e12-823c-d60cf749481c