apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::315069654700:role/eksctl-roboshop-cluster-nodegroup--NodeInstanceRole-yZS3T6m0Z2Am
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::490004616197:user/bhavana  
      username: bhavana
      groups:
      # - pod-reader these are not mandatory to mention here if you create role and rolebindings they can automatically gets used to it
      # - service-reader  mentioning user is mandatory
      # - secret-reader
      
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
  uid: 11571167-16ab-4e12-823c-d60cf749481c # this should be need to get from our original eks cluster