apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: roboshop
  labels:
    app: backend
    project: roboshop
    tier: app
spec:
  replicas: {{ .Values.deployment.replicas}}
  selector:
    matchLabels:
      app: backend
      project: roboshop
      tier: app
  template:
    metadata:
      labels:
        app: backend
        project: roboshop
        tier: app
    spec:
      containers:
      - name: backend
        image: "hitesh2201/backend:{{ .Values.deployment.imageVersion}}"
        resources:
          limits:
            cpu: 150m
          requests:
            cpu: 125m
        envFrom:
        - configMapRef:
            name: backend
