apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: roboshop
  labels:
    app: backend
    project: roboshop
    tier: app
spec:
  ports:
  - name: backend
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: backend
    project: roboshop
    tier: app